import uuid

from pydantic import BaseModel, Field, field_validator


class AskRequest(BaseModel):
    """Input query and scoping filter parameters for grounded LLM answer generation."""

    query: str = Field(
        ...,
        min_length=1,
        max_length=1000,
        description="Factual research question to answer",
    )
    top_k: int = Field(
        5,
        ge=1,
        le=100,
        description="Maximum number of context chunks to retrieve and evaluate",
    )
    document_ids: list[uuid.UUID] | None = Field(
        None,
        description="Optional list of document UUIDs to restrict the evidence retrieval scope to",
    )
    file_types: list[str] | None = Field(
        None,
        description="Optional list of file extensions (e.g. .pdf, .txt) to narrow search scope",
    )
    conversation_id: uuid.UUID | None = Field(
        None,
        description="Optional active conversation session UUID",
    )

    @field_validator("query")
    @classmethod
    def validate_non_empty(cls, value: str) -> str:
        if not value or not value.strip():
            raise ValueError("Query string cannot be empty or whitespace only.")
        return value


class SourceLocation(BaseModel):
    """Generic source location containing optional, file-type-specific location coordinates."""

    page_number: int | None = Field(None, description="Page number where the chunk text is located")
    section_title: str | None = Field(None, description="Document section header title")
    paragraph_index: int | None = Field(None, description="DOCX paragraph index")
    sheet_name: str | None = Field(None, description="Excel spreadsheet tab name")
    row_start: int | None = Field(None, description="Excel/CSV row start index")
    row_end: int | None = Field(None, description="Excel/CSV row end index")
    column_range: str | None = Field(None, description="Excel column ranges")
    json_path: str | None = Field(None, description="JSON path within structured files")
    line_start: int | None = Field(None, description="Text line start index")
    line_end: int | None = Field(None, description="Text line end index")


class SourceReference(BaseModel):
    """Traceable citation mapping a generated reference back to the backend retrieved context chunk."""

    source_id: str = Field(..., description="Stable reference identifier (e.g. S1)")
    document_id: uuid.UUID = Field(..., description="UUID of the parent Document")
    chunk_id: uuid.UUID = Field(..., description="UUID of the specific context chunk")
    filename: str = Field(..., description="Name of the source document file")
    location: SourceLocation = Field(..., description="File-specific location coordinates")
    relevance_score: float = Field(..., description="Relevance score computed by vector search or reranker")
    preview: str = Field(..., description="Short truncated preview of the chunk text")


class RAGResponse(BaseModel):
    """Structured response containing the grounded answer text and unique cited source metadata."""

    query: str = Field(..., description="Echo of the input query string")
    answer: str = Field(..., description="Grounded factual answer generated by the LLM from evidence")
    citations: list[SourceReference] = Field(
        ...,
        description="Deterministic list of resolved citations in order of first appearance in the answer",
    )
    conversation_id: uuid.UUID | None = Field(
        None,
        description="Active conversation session UUID associated with this query",
    )
